# Generated by Django 4.2.2 on 2023-06-28 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_customuser_subscribed'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='subscribed',
            field=models.BooleanField(default=False),
        ),
    ]
